---
name: CMPSC 302: Simon
break: true
indent: 4
---

docs/style/style.css:
  MatchFileFragment --fragment "TODO" --count 0 --exact --description "[CSS] style.css contains no TODOs"
  MatchFileFragment --fragment "grid" --count 1 --description "[CSS] style.css creates at least one grid-based element"
  MatchFileFragment --fragment "@media only screen and (max-width: 1024px)" --count 1 --exact --description "[CSS] style.css uses a mobile query at 700px breakpoint"

docs/index.html:
  MatchFileFragment --fragment "TODO" --count 0 --exact --description "[HTML] index.html contains no TODOs"
  MatchFileFragment --fragment "

ExecuteCommand --command "html5validator --root docs/" --description "[HTML] The docs/ directory passes W3C validation"
ExecuteCommand --command "html5validator --root docs/style --skip-non-css" --description "[CSS] The docs/ directory passes W3C validation"
ExecuteCommand --command "config/.check.py button 5" --description "[HTML] There are at least 5 <button>s"

